sudo: required
dist: trusty

# https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-with-the-APT-Addon
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: "node_js"
node_js:
  - "8"

# https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
cache:
  yarn: true

# http://docs.travis-ci.com/user/gui-and-headless-browsers
before_install:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - "gulp dist"

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false

# https://docs.travis-ci.com/user/deployment/npm/
deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: q6MZ1izQ8WmG1fWYzvaoSLM0OKn5E8ACdh2oM16jnqDVC0zkcW55/pDudALAQ3mIp4Z+ystusu2Rq5OyMIKjqmpx69qV3czHIhHd4m825dmTBnZ3kKSvelq8PAcJsgXFn245GBd8zFtgLYpuG/KjANVg3ub5ia7wtyKky0kmKQxM3JdupiinIWc1GdPOKy7vG9Sh7Bbri505HC8r8lnx3eFhi9bzPlXqIoG+Cv2FaRh2bCSrupfX4itv4CccVZKVpN21X8pq0Qm+p0U7yRER68Bip3h2ZrCxmJPg/g05w5369lPX29+F1gssi5AYA6DVzwJUURtcfa2Ib0WSRzvlSgXky2qGpdF/aNoGJ3Scy2//w7BlRDHykf+TgWjz2fp+9X5NZ81xU0rI2ClbOer9p89HUO+zQeATFht0XntUeL5fOlvAg+SWQmuxIPqQH3KQ+Ou857Bk81ZqtmmAJOvT9EsrO4QU38vi8VmL++Ilu9JXfibTFgpHYWNn7pa18ab1iRQzPBKaiNLEN9ijgEvNs7KzcSTin8CNeEEO0wxGCuc0pWH5LjzDrSKfYOygo/IYyedDpbsqVPcsF81EfqpfJBWXnYnYAsHGMF2MUF0wz4XnsE+uJhIIY/Efc7NlzQhdXdCc8G9vZjIF1YK8i5B6/ZN3q8GdaGoErtM5HktuABI=
  api_key:
    secure: NGPmECsDCQ43uwTGlKkyOrb2IMJ7tTLzHvxMYeHBTQ/OR4i5fTABaWUdSqbQbgzLqHAFyqU9xbQfKApuQY8EQ/TZgoFssDWQwrqEaT+F3ny2MymCtZCfbgycVaQZgcJTlUAuo58yRtOfMA7DVOafTnaoAmtHotpuzqfypzvgG1HPS4yaUZid7liHWoHLUAgfmEc4DKgUu1+wBL1NqAM7nZ09P3SwqdCSUu48BWJgHMZaSbc/Xnaz+1+5pdThwh4c/7JM+DaSUKwLFXgarMYLvgbyTwVly2HQ/Z8EHFvj5OAHlG85nK6btS2CG2h1rNGLR1mnfGCaKl9MLJi70Ks8qbbq1BqX4lTvnLJAcK1LlMbS1FZnuR1sxU5XAshxwiJ2CVVli0kLFE8HSdSjDbZUKZac4uMNF03AgDWuh1TLVX2rw/8EmW6mE3geEKTwB2nwcz9K8f43LTRPKsGJpMkbEa6M0ibTnSMOE+TEz7JVbffNNYCqY2dAyfs8QdMBVRygmDASifx7fa2tESRIkIRBOJiOmNjqbaEnyOYEc54VbkNz6NiCoQjs1YNeYCbweS9Q669lpw0I8UMSH69LcqRBW8uekqHaCTAzRBsFpoXVNfu71VB0btYrl2tKwQPcCU1frXmBG8tRpVsouSaPoBfNYKSJnjNnwjuGJVq1AypQOYs=
  on:
    tags: true
